# Generated by Django 4.2 on 2023-07-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("numberOfTickets", models.IntegerField()),
                ("description", models.TextField()),
                ("pricePerTicket", models.FloatField()),
                ("drawDate", models.DateField()),
                ("drawTime", models.TimeField()),
            ],
        ),
    ]
