# Generated by Django 4.2 on 2023-07-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=25)),
                ("city", models.CharField(max_length=127)),
                ("neighborhood", models.CharField(max_length=200)),
                ("street", models.CharField(max_length=200)),
                ("houseNumber", models.CharField(max_length=127)),
                ("reference", models.TextField(null=True)),
                ("zipCode", models.CharField(max_length=12)),
            ],
        ),
    ]
